(model-evaluation)=
# Model Evaluation Metrics

### gamlss_main.Gamlss.<br>**evaluate**

```python
evaluate(test_data, train_data, func_name=None, handle_outliers=True, affected=None,
         affected_col_name='affected', use_transfer=False, gam_refit_path=None,
         adjustment_covariates=None, params_to_adjust=None, treat_missing_as_healthy=False)
```

&nbsp;&nbsp;&nbsp;&nbsp;Calculates six key evaluation metrics for assessing GAMLSS model quality:

1. **Z_Scores_Mean**: Mean of normalized quantile residuals (z-scores) (should ≈ 0)
2. **Z_Scores_SD**: Standard deviation of normalized quantile residuals (z-scores) (should ≈ 1)  
3. **Logarithmic_Score**: Mean log probability density (higher values indicate better fit)
4. **Skewness**: Bias-corrected asymmetry measure (values close to 0 indicate symmetry)
5. **Kurtosis**: Bias-corrected excess kurtosis (values close to 0 indicate appropriate tail behavior)
6. **Normality_Test_Statistic**: Adaptive normality test (Shapiro-Wilk for n≤5000, Anderson-Darling for n>5000)

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data for evaluation

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data used for model fitting

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**func_name** : ***str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Distribution family name. If None (default), the model's own family is used; a different family raises an error

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**handle_outliers** : ***bool***, *default=True* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to apply censoring for extreme values at 1st and 99th percentiles

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**affected** : ***array-like***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Array indicating affected status for filtering to healthy subjects only. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If None, attempts to use column specified by `affected_col_name` from test_data. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If neither array nor column exists, assumes all subjects are healthy. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Supports multiple formats: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **`'None'`**: the text `'None'` is treated as healthy <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Missing values**: `np.nan` or `None` raise a `ValueError`, unless `treat_missing_as_healthy=True` <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Binary masking**: `0` = healthy, `1` (or non-zero) = affected <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Healthy labels**: the whole label is `'healthy'`, `'healthy control'`, `'healthy controls'`, `'control'` or `'controls'` (any case, e.g. `'Healthy'`, `'HEALTHY'`, `'Healthy Control'`) <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;labels that mention 'healthy' or 'control' but are not on this list (e.g. `'healthy subject'`, `'HealthyControl'`, `'unhealthy'`) raise an error asking you to rename them; any other string (e.g. `'MDD'`) is treated as affected <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**affected_col_name** : ***str***, *default='affected'* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name of the column in test_data to use for identifying healthy subjects. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only used if `affected` parameter is None. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Supports the same formats as the `affected` array (`'None'`, binary, strings).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**use_transfer** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If True, use site transfer adjustments for predictions and z-scores. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Requires `gam_refit_path` to be provided.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**gam_refit_path** : ***str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Path to saved adjustment model (.rds file). <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Required when `use_transfer=True`. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Should be obtained from `multisite_transfer()` results.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**adjustment_covariates** : ***list of str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Column names in test_data used as covariates in the adjustment model. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only needed if `use_transfer=True` and the transfer model was fitted with covariates. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Required when the adjustment model has covariate terms; leaving it out then raises an error (default is None).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**params_to_adjust** : ***list of str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Parameters the transfer adjusted (`site_transfer`'s `params_to_adjust`). Only used if `use_transfer=True`. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If None (default), read from the saved adjustment model itself; if given, it must match what the transfer adjusted (an error is raised otherwise).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**treat_missing_as_healthy** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether subjects with a missing status (`np.nan` or `None`) count as healthy. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;By default they raise a `ValueError`, because a missing diagnosis is not a healthy one. The text `'None'` is always healthy, whatever this is set to. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Note that `pd.read_csv` reads the text `None` as missing; read the file with `pd.read_csv(..., keep_default_na=False, na_values=[''])` to keep it.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**results_df** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame with two columns: 'Metric' and 'Value' containing six evaluation metrics

<br>

**Examples:**

```python
# Example 1: Using binary masking (0 = healthy, 1 = affected)
affected_binary = np.array([0, 0, 1, 0, 1, 0, 0, 1])
results = model.evaluate(test_data, train_data, affected=affected_binary)

# Example 2: Using the text 'None' for healthy subjects
affected_none = np.array(['None', 'None', 'Disease A', 'None', 'Disease B', 'None'])
results = model.evaluate(test_data, train_data, affected=affected_none)
# 'None' → treated as healthy
# 'Disease A', 'Disease B' → treated as affected
# A missing status (np.nan or None) raises a ValueError; pass
# treat_missing_as_healthy=True only if missing really means healthy

# Example 3: Using healthy labels (whole label, case-insensitive)
affected_strings = np.array(['Healthy', 'Healthy Control', 'Affected',
                             'HEALTHY', 'MDD', 'controls'])
results = model.evaluate(test_data, train_data, affected=affected_strings)
# 'Healthy', 'Healthy Control', 'HEALTHY', 'controls' → treated as healthy
# 'Affected', 'MDD' → treated as affected
# Labels such as 'healthy subject', 'HealthyControl' or 'unhealthy' raise a
# ValueError: rename them to a healthy label (or 'None') or to a condition name

# Example 4: No affected parameter (all subjects assumed healthy)
results = model.evaluate(test_data, train_data)
```
<br>

**Notes:**

- Evaluation is performed only on healthy subjects identified through the `affected` parameter
- The method automatically filters out affected subjects before calculating metrics
- The number of healthy subjects used is printed during execution
- If no healthy subjects are found after filtering, a `ValueError` is raised
- A missing status (`np.nan` or `None`) raises a `ValueError`, unless `treat_missing_as_healthy=True`

**Examples 1:**

In [15]:
import numpy as np

# To check how many healthy subjects we have
len(test_data1[test_data1['affected']=='None'])

370

In [16]:
gamlss_model.evaluate(test_data = test_data1, affected=test_data1['affected'], train_data=df_train)

Using 370 healthy subjects out of 470 total subjects for evaluation

                     Metric     Value
1             Z_Scores_Mean  0.038786
2               Z_Scores_SD  0.995145
3         Logarithmic_Score -1.462897
4                  Skewness -0.019956
5                  Kurtosis -0.520425
6  Normality_Test_Statistic  0.992989

**Examples 2:**

In [17]:
## Get the None value index and create a masking array
none_indices = test_data1[test_data1['affected']=='None'].index
affected_arr = np.ones(len(test_data1))
affected_arr[none_indices] = 0

In [18]:
gamlss_model.evaluate(test_data = test_data1, affected=affected_arr, train_data=df_train)

Using 370 healthy subjects out of 470 total subjects for evaluation

                     Metric     Value
1             Z_Scores_Mean  0.038786
2               Z_Scores_SD  0.995145
3         Logarithmic_Score -1.462897
4                  Skewness -0.019956
5                  Kurtosis -0.520425
6  Normality_Test_Statistic  0.992989

### gamlss_main.Gamlss.<br>**evaluate_ml**

```python
evaluate_ml(test_data, train_data, transform=True, verbose=False, affected=None,
            affected_col_name='affected', use_transfer=False, gam_refit_path=None,
            adjustment_covariates=None, params_to_adjust=None, treat_missing_as_healthy=False)
```

&nbsp;&nbsp;&nbsp;&nbsp;Calculates six machine learning evaluation metrics for assessing predictive performance:

1. **MAE**: Mean Absolute Error (lower values indicate better predictions)
2. **MSE**: Mean Squared Error (lower values indicate better predictions)
3. **RMSE**: Root Mean Squared Error (lower values indicate better predictions)
4. **R_Squared**: Coefficient of determination (values closer to 1 indicate better fit)
5. **MAPE**: Mean Absolute Percentage Error (lower percentages indicate better accuracy)
6. **Mean_Error**: Prediction bias (values close to 0 indicate unbiased predictions)

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data for evaluation

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data used for model fitting

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**transform** : ***bool***, *default=True* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to apply transformations for predictions

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**verbose** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to print detailed information during evaluation   <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**affected** : ***array-like***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Array indicating affected status for filtering to healthy subjects only. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If None, attempts to use column specified by `affected_col_name` from test_data. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If neither array nor column exists, assumes all subjects are healthy. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Supports multiple formats: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **`'None'`**: the text `'None'` is treated as healthy <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Missing values**: `np.nan` or `None` raise a `ValueError`, unless `treat_missing_as_healthy=True` <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Binary masking**: `0` = healthy, `1` (or non-zero) = affected <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Healthy labels**: the whole label is `'healthy'`, `'healthy control'`, `'healthy controls'`, `'control'` or `'controls'` (any case, e.g. `'Healthy'`, `'HEALTHY'`, `'Healthy Control'`) <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;labels that mention 'healthy' or 'control' but are not on this list (e.g. `'healthy subject'`, `'HealthyControl'`, `'unhealthy'`) raise an error asking you to rename them; any other string (e.g. `'MDD'`) is treated as affected <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**affected_col_name** : ***str***, *default='affected'* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name of the column in test_data to use for identifying healthy subjects. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only used if `affected` parameter is None. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Supports the same formats as the `affected` array (`'None'`, binary, strings).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**use_transfer** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If True, use site transfer adjustments for predictions and z-scores. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Requires `gam_refit_path` to be provided.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**gam_refit_path** : ***str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Path to saved adjustment model (.rds file). <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Required when `use_transfer=True`. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Should be obtained from `multisite_transfer()` results.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**adjustment_covariates** : ***list of str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Column names in test_data used as covariates in the adjustment model. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only needed if `use_transfer=True` and the transfer model was fitted with covariates. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Required when the adjustment model has covariate terms; leaving it out then raises an error (default is None).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**params_to_adjust** : ***list of str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Parameters the transfer adjusted (`site_transfer`'s `params_to_adjust`). Only used if `use_transfer=True`. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If None (default), read from the saved adjustment model itself; if given, it must match what the transfer adjusted (an error is raised otherwise).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**treat_missing_as_healthy** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether subjects with a missing status (`np.nan` or `None`) count as healthy. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;By default they raise a `ValueError`, because a missing diagnosis is not a healthy one. The text `'None'` is always healthy, whatever this is set to. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Note that `pd.read_csv` reads the text `None` as missing; read the file with `pd.read_csv(..., keep_default_na=False, na_values=[''])` to keep it.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**results_df** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame with two columns: 'Metric' and 'Value' containing six ML evaluation metrics

<br>

**Examples:**

In [19]:
df_test = test_data1.loc[:, columns]
gamlss_model.evaluate_ml(test_data = test_data1, affected = test_data1['affected'], train_data = df_train)

Using 370 healthy subjects out of 470 total subjects for evaluation

       Metric     Value
0         MAE  0.943362
1         MSE  1.225695
2        RMSE  1.107111
3   R_Squared  0.419698
4        MAPE  3.993906
5  Mean_Error -0.050823

### gamlss_main.Gamlss.<br>**evaluate_detailed**

```python
evaluate_detailed(test_data, train_data, func_name=None, handle_outliers=True,
                  transform=True, verbose=False, affected=None, affected_col_name='affected',
                  use_transfer=False, gam_refit_path=None, adjustment_covariates=None,
                  params_to_adjust=None, treat_missing_as_healthy=False)
```

&nbsp;&nbsp;&nbsp;&nbsp;Calculates comprehensive evaluation metrics combining GAMLSS-specific, ML, and information criteria metrics for complete model assessment. Returns all 14 metrics organized by category:

**GAMLSS Metrics (6):** Z_Scores_Mean, Z_Scores_SD, Logarithmic_Score, Skewness, Kurtosis, Normality_Test_Statistic

**ML Metrics (6):** MAE, MSE, RMSE, R_Squared, MAPE, Mean_Error

**Information Criteria (2):** AIC, BIC

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Parameters:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**test_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the test data for evaluation

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**train_data** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame containing the training data used for model fitting

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**func_name** : ***str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Distribution family name. If None (default), the model's own family is used; a different family raises an error

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**handle_outliers** : ***bool***, *default=True* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to apply censoring for extreme values in GAMLSS metrics

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**transform** : ***bool***, *default=True* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to apply transformations for ML predictions

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**verbose** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether to print detailed information and interpretation guidance  <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**affected** : ***array-like***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Array indicating affected status for filtering to healthy subjects only. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If None, attempts to use column specified by `affected_col_name` from test_data. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If neither array nor column exists, assumes all subjects are healthy. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Supports multiple formats: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **`'None'`**: the text `'None'` is treated as healthy <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Missing values**: `np.nan` or `None` raise a `ValueError`, unless `treat_missing_as_healthy=True` <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Binary masking**: `0` = healthy, `1` (or non-zero) = affected <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• **Healthy labels**: the whole label is `'healthy'`, `'healthy control'`, `'healthy controls'`, `'control'` or `'controls'` (any case, e.g. `'Healthy'`, `'HEALTHY'`, `'Healthy Control'`) <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;labels that mention 'healthy' or 'control' but are not on this list (e.g. `'healthy subject'`, `'HealthyControl'`, `'unhealthy'`) raise an error asking you to rename them; any other string (e.g. `'MDD'`) is treated as affected <br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**affected_col_name** : ***str***, *default='affected'* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name of the column in test_data to use for identifying healthy subjects. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only used if `affected` parameter is None. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Supports the same formats as the `affected` array (`'None'`, binary, strings).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**use_transfer** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If True, use site transfer adjustments for predictions and z-scores. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Requires `gam_refit_path` to be provided.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**gam_refit_path** : ***str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Path to saved adjustment model (.rds file). <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Required when `use_transfer=True`. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Should be obtained from `multisite_transfer()` results.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**adjustment_covariates** : ***list of str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Column names in test_data used as covariates in the adjustment model. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Only needed if `use_transfer=True` and the transfer model was fitted with covariates. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Required when the adjustment model has covariate terms; leaving it out then raises an error (default is None).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**params_to_adjust** : ***list of str***, *optional* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Parameters the transfer adjusted (`site_transfer`'s `params_to_adjust`). Only used if `use_transfer=True`. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If None (default), read from the saved adjustment model itself; if given, it must match what the transfer adjusted (an error is raised otherwise).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**treat_missing_as_healthy** : ***bool***, *default=False* <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Whether subjects with a missing status (`np.nan` or `None`) count as healthy. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;By default they raise a `ValueError`, because a missing diagnosis is not a healthy one. The text `'None'` is always healthy, whatever this is set to. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Note that `pd.read_csv` reads the text `None` as missing; read the file with `pd.read_csv(..., keep_default_na=False, na_values=[''])` to keep it.

&nbsp;&nbsp;&nbsp;&nbsp;<span style="background-color: #f5f5f5; padding: 4px 8px; display: inline-block; width: 90%;">**Returns:**</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**results_df** : ***pandas.DataFrame*** <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataFrame with three columns: 'Category', 'Metric', 'Value' containing all 14 evaluation metrics

<br>

**Examples:**

In [20]:
df_test = test_data1.loc[:, columns]
gamlss_model.evaluate_detailed(test_data = test_data1, affected = test_data1['affected'], train_data = df_train, verbose=False)

Using 370 healthy subjects out of 470 total subjects for evaluation
Using 370 healthy subjects out of 470 total subjects for evaluation

                Category                    Metric        Value
0                 GAMLSS             Z_Scores_Mean     0.038786
1                 GAMLSS               Z_Scores_SD     0.995145
2                 GAMLSS         Logarithmic_Score    -1.462897
3                 GAMLSS                  Skewness    -0.019956
4                 GAMLSS                  Kurtosis    -0.520425
5                 GAMLSS  Normality_Test_Statistic     0.992989
6                     ML                       MAE     0.943362
7                     ML                       MSE     1.225695
8                     ML                      RMSE     1.107111
9                     ML                 R_Squared     0.419698
10                    ML                      MAPE     3.993906
11                    ML                Mean_Error    -0.050823
12  Information_Criteria                       AIC  3065.477334
13  Information_Criteria                       BIC  3119.575818